[package]
name = "kaleidoscope-rs"
version = "0.1.0"
edition = "2021"

[worksapce]
members = [
    "crates/*"
]

[dependencies]
libc = "0.2.166"
# inkwell = "0.5.0"
llvm-sys = "191"
thiserror = "2.0.3"
