[package]
name = "kaleidoscope-rs"
version = "0.1.0"
edition = "2021"

[worksapce]
members = [
    "crates/*"
]

[dependencies]
llvm-bind = { version = "0.1.0", path = "crates/llvm-bind" }
llvm-sys = "191"
thiserror = "2.0.3"
